version: '3.7'

services:
  db:
    image: postgres:12-alpine
    container_name: db
    environment:
      - POSTGRES_USER=pixies
      - POSTGRES_PASSWORD=pixies
      - POSTGRES_DB=pixies
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
