version: '3.7'

services:
  db:
    image: postgres:12-alpine
    container_name: db
    environment:
      - POSTGRES_DB=pixies
      - POSTGRES_NAME=pixies
      - POSTGRES_USER=pixies
      - POSTGRES_PASSWORD=pixies
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

  backend:
    build: .
    environment:
      - PORT=80
      - SECRET_KEY=hushush
      - DATABASE_URL=postgresql://pixies:pixies@db:5432/pixies
      - ALLOWED_HOSTS=*
    ports:
      - 9090:80
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
    ports:
      - 9091:80
    environment:
      - PORT=80
    depends_on:
      - backend

volumes:
  data:
